config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :users

  # Sign up
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  # Session
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # Defines the root path route ("/")
  root to: 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates_presence_of :title, message: 'title is required'
  validates_presence_of :author_name, message: 'author_name required'
  validates_presence_of :first_publish_year, message: 'first_publish_year is required'
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
# email: string
# password_digest: string
#
# password: string virtual
# password_confirmation: string virtual
class User < ApplicationRecord
  has_secure_password
  has_many :books

  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Must be a valid Email address.' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: 'You must be signed in to do that.' if Current.user.nil?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]
  before_action :require_user_logged_in!

  # GET /books or /books.json
  def index
    # Kaminari
    @books = Book.order(created_at: :desc).page(params[:page]).per(10)
  end

  # GET /books/1 or /books/1.json
  def show; end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit; end

  # POST /books or /books.json
  def create
    @book = Current.user.books.create(book_params)

    # Action Cable
    if @book.save
      data = ApplicationController.render partial: 'books/single_book', locals: { book: @book }
      ActionCable.server.broadcast 'books_channel', data
      redirect_to root_path, notice: 'Book was successfully registered'
    else
      flash[:alert] = 'Something happened while trying to register a Book, try again.'
      render :new
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  # Make it so that only the user that registered the book can patch it
  def update
    if Current.user.id == @book.user_id
      respond_to do |format|
        if @book.update(book_params)
          format.html { redirect_to root_path, notice: 'Book was successfully updated.' }
          format.json { render :show, status: :ok, location: @book }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:alert] = 'You are not allowed to edit this book.'
      redirect_to root_path
    end
  end

  # DELETE /books/1 or /books/1.json
  # Make it so that only the user that registered the book can delete it
  def destroy
    if Current.user.id == @book.user_id

      @book.destroy

      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Book was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      flash[:alert] = 'You are not allowed to delete this book.'
      redirect_to root_path
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :author_name, :first_publish_year, :cover_edition_key)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    # Kaminari
    @books = Book.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Sucessfully created account'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully'
    else
      flash[:alert] = 'Something went wrong try again'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'logged out'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
   <div class="single-book">
      <% if book.cover_edition_key %>
       <%= image_tag book.cover_edition_key, alt:"testImgL.jpg", class: "card-img-left img-fluid me-3 rounded float-left book-image" %>
     <% else %>
       <%= image_tag "testImgL.jpg", class: "img-fluid me-3 rounded float-left book-image" %>
      <% end %>

      <div class="book-body"> 
          <h5 class="book-title">
            <%= book.title %>
          </h5>
          <p class="book-author">
            <%= book.author_name %>
          </p>
          <small class="book-year">
            <%= book.first_publish_year %> 
          </small>
      </div>
      
      <div>
        <td><%= link_to "Edit this book", edit_book_path(book) %> </td> 
       <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
 
      </div>
   </div>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, style: "display: block", class:"tc-white" %>
    <%= form.text_field :title, class:"bg-l2-grey tc-l-grey rounded-pill" %>
  </div>

  <div class="field">
    <%= form.label :author_name , style: "display: block", class:"tc-white" %>
    <%= form.text_field :author_name, class:"bg-l2-grey tc-l-grey rounded-pill" %>
  </div>

  <div class="field">
    <%= form.label :first_publish_year , style: "display: block", class:"tc-white" %>
    <%= form.number_field :first_publish_year, class:"bg-l2-grey tc-l-grey rounded-pill" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/_single_book.erb
 <div class="single-book">
    <% if book.cover_edition_key %>
     <%= image_tag book.cover_edition_key, class: "card-img-left img-fluid me-3 rounded float-left book-image" %>
   <% else %>
     <%= image_tag "testImgL.jpg", class: "img-fluid me-3 rounded float-left book-image" %>
    <% end %>

    <div class="book-body"> 
        <h5 class="book-title tc-l-grey">
          <%= book.title %>
        </h5>
        <p class="book-author tc-l-grey">
          <%= book.author_name %>
        </p>
        <small class="book-year tl-grey">
          <%= book.first_publish_year %> 
        </small>
    </div>
      <div class="double-buttons rounded-pill m-1">
        <%= link_to "Update", edit_book_path(book), class: "btn btn-primary" %>
        <%= button_to 'Destroy', book, method: :delete, class: "btn btn-danger" %>
      </div>

 </div>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>


   <%# Show only user books %>


<div id="books" class="book-list-container gap-3 mt-4">
    <% @books.each do |book| %>
      <%= render book, book: book %>
    <% end %>
</div>

<div class="pages">
  <%= paginate @books %>
</div>

app/views/books/new.html.erb
<div id="books-page" class="form-outline mt-4">
   <%= form_with model: @book, url: books_path do |form| %>
    <div class="add-book-page-outter-div">
        <%= form.text_field :search, class: "search-box form-control m-3 bg-l2-grey tc-l-grey", placeholder:"Search books", href: "#", id: "search-bar", role: "button", "data-bs-toggle": "dropdown", "aria-expanded": "false", autocomplete: "off" %>
          <div class="add-book-page-selection mt-2">
              <div class="add-book-page-fields">
                <div class="field">
                  <%= form.label :title, style: "display: block", class:"tc-white" %>
                  <%= form.text_field :title, class:"bg-l2-grey tc-l-grey rounded-pill" %>
                </div>
                <div class="field">
                  <%= form.label :author_name , style: "display: block", class:"tc-white" %>
                  <%= form.text_field :author_name, class:"bg-l2-grey tc-l-grey rounded-pill" %>
                </div>
                <div class="field">
                  <%= form.label :first_publish_year , style: "display: block", class:"tc-white" %>
                  <%= form.number_field :first_publish_year, class:"bg-l2-grey tc-l-grey rounded-pill" %>
                </div>
                  <%= form.text_field :cover_edition_key, type: "hidden" %>
                  <%= form.submit class:"btn btn-primary book-create rounded-pill mt-2 m-1"%>
                </div>
              <div id="search-list", class="book-list-container gap-3 mt-4" aria-labelledby="search"></div>
            </div>
        </div>  
      </div>
   <% end %>
</div>

app/views/books/show.html.erb
   <div class="single-book">
      <% if @book.cover_edition_key %>
       <%= image_tag @book.cover_edition_key, alt:"/images/testImgL.jpg", class: "card-img-left img-fluid me-3 rounded float-left book-image" %>
     <% else %>
       <%= image_tag "testImgL.jpg", class: "img-fluid me-3 rounded float-left book-image" %>
      <% end %>

      <div class="book-body"> 
          <h5 class="book-title tc-l-grey">
            <%= @book.title %>
          </h5>
          <p class="book-author tc-l-grey">
            <%= @book.author_name %>
          </p>
          <small class="book-year tc-l-grey">
            <%= @book.first_publish_year %> 
          </small>
      </div>
      
      <div>
        <td><%= link_to "Edit this book", edit_book_path(@book) %> </td> 

       <%= button_to 'Destroy', @book, method: :delete %>
      </div>
   </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookRegistrationSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div id="home-page"> 
<div id= "all-books" class="book-list-container gap-3 mt-4">
   <% @books.each do |book| %> 
      <div class="single-book">
          <% if book.cover_edition_key %>
           <%= image_tag book.cover_edition_key, class: "card-img-left img-fluid me-3 rounded float-left book-image" %>
         <% else %>
           <%= image_tag "testImgL.jpg", class: "img-fluid me-3 rounded float-left book-image" %>
          <% end %>

          <div class="book-body"> 
              <h5 class="book-title tc-l-grey">
                <%= book.title %>
              </h5>
              <p class="book-author tc-l-grey">
                <%= book.author_name %>
              </p>
              <small class="book-year tc-l-grey">
                <%= book.first_publish_year %> 
              </small>
          </div>
          
          <div class="double-buttons rounded-pill m-1">
            <%= link_to "Update", edit_book_path(book), class: "btn btn-primary" %>
            <%= button_to 'Destroy', book, method: :delete, class: "btn btn-danger" %>
          </div>
      </div>
       <% end %> 
   </div> 

</div>
<div class="pages"> 
   <div class="mt-4 pages"> 
     <%= paginate @books %> 
   </div> 
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4">
   <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
 <div class="alert alert-warning mt-4">
  <%= flash[:alert] %>
 </div> 
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-d-grey">
  <div class="container-fluid">
    <%= link_to "Book Registration System", root_path, class: "navbar-brand tc-white" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link tc-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Register a book", new_book_path, class: "nav-link tc-white" %>
        </li>
         <li class="nav-item">
          <%= link_to "My Books", books_path, class: "nav-link disabled tc-m-grey" %>
        </li>

     </ul>
      <ul class ="navbar-nav ms-auto mb-2 mb-lg-0 my-navbar">
          <% if Current.user %>
               <li class="nav-item user-email tc-l-grey">  
                 <h5><%=  Current.user.email%>  </h5>
              </li>
              <li class="nav-item">
                <%=  button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-danger" %>
              </li>
          <% else %>
              <li class="nav-item">
                <%= link_to "Login", sign_in_path, class: "nav-link tc-l-grey" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign Up", sign_up_path, class: "nav-link tc-l-grey"  %>
              </li>
          <% end %>
        </ul>
    </div>
  </div>
</nav>